version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  generate:
    desc: generate database and handlers code
    cmds:
      - |
        docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
          -i "$OPENAPI_SPEC" \
          --additional-properties packageName=emaildetective \
          -g go \
          -o /local
      - rm git_push.sh
      - go get github.com/stretchr/testify/assert
      - grep -rl "GIT_USER_ID" | grep -v "Taskfile.yaml" | xargs sed -i.bak 's/GIT_USER_ID/AndrewCopeland/g'
      - grep -rl "GIT_REPO_ID" | grep -v "Taskfile.yaml" | xargs sed -i.bak 's/GIT_REPO_ID/go-ipdetective/g'
      - grep -rl "openapiclient" | grep -v "Taskfile.yaml" | xargs sed -i.bak 's/openapiclient/ipdetective/g'
      - find . -type f -name "*.bak" -not -path "*/.git/*" -exec rm {} +
  push:
    desc: push a new version
    cmds:
      - git tag -a $TAG -m "Version $TAG"
      - git push origin --tags
